spring.application.name=mascotas

spring.datasource.url=jdbc:mysql://localhost:3306/mascotas_db
spring.datasource.username=root
spring.datasource.password=1234

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración SMTP de Gmail
#Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emaildepruebasprint@gmail.com
spring.mail.password=abpz tcin nfil oljq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.transport.protocol=smtp
spring.mail.debug=true